Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.72.128:3000"
  copyright: Copyright (c) 2012, Hideyuki Tanaka
  analytics: UA-31489536-1

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://hackage.haskell.biz"
  <<: *defaults
